# Stack config for ghc-dump-tree, for ease of building for multiple GHC versions.
# 1) Install stack.
# 2) Change the resolver option below to the GHC you like.
# 3) stack build
# 4) stack exec <the binary path you got in previous step>/ghc-dump-tree Some.hs
#
#    stack exec is needed so that the correct GHC libs are taken up from env.
#    See also 'stack exec env'.
#
# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

resolver: lts-14.7  # GHC 8.6.5

# Local packages, usually specified by relative directory name
packages:
- '.'
